version: '3.7'
services:

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: python main.py
    tty: true

    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      PYTHONPATH: .
