version: '3.7'
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: python main.py
    tty: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      PYTHONPATH: .

  wg-client2:
    image: linuxserver/wireguard
    container_name: "wg-client2"
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PEERDNS=auto
      - LOG_CONFS=true
    volumes:
      - "./backend/data/client1:/config"