"""Add private and public keys columns to wireguard interface

Revision ID: 3ea4da90d033
Revises: d6bad04647c0
Create Date: 2023-07-18 20:01:56.431862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ea4da90d033'
down_revision = 'd6bad04647c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wireguard_interface', sa.Column('private_key', sa.String(), nullable=True))
    op.add_column('wireguard_interface', sa.Column('public_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wireguard_interface', 'public_key')
    op.drop_column('wireguard_interface', 'private_key')
    # ### end Alembic commands ###
