"""Add on_down column to wireguard interface

Revision ID: d6bad04647c0
Revises: ea7de0b64f3e
Create Date: 2023-07-11 20:56:44.904532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd6bad04647c0'
down_revision = 'ea7de0b64f3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wireguard_interface', sa.Column('on_down', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wireguard_interface', 'on_down')
    # ### end Alembic commands ###
