"""Added wireguard tables

Revision ID: ea7de0b64f3e
Revises: 91979b40eb38
Create Date: 2023-07-11 02:04:08.572291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ea7de0b64f3e'
down_revision = '91979b40eb38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'wireguard_interface',
        sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('gateway_interface', sa.String(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('ip_address', postgresql.INET(), nullable=True),
        sa.Column('listen_port', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(length=125), nullable=True),
        sa.Column('on_up', postgresql.ARRAY(sa.String()), nullable=True),
        sa.PrimaryKeyConstraint('uuid'),
        sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_wireguard_interface_uuid'), 'wireguard_interface', ['uuid'], unique=False)
    op.create_table(
        'wireguard_interface_peer',
        sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('interface_id', sa.UUID(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('dns1', postgresql.INET(), nullable=True),
        sa.Column('dns2', postgresql.INET(), nullable=True),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('private_key', sa.String(), nullable=True),
        sa.Column('public_key', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['interface_id'], ['wireguard_interface.uuid'], ),
        sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_wireguard_interface_peer_uuid'), 'wireguard_interface_peer', ['uuid'], unique=False)
    op.alter_column(
        'user', 'is_active',
        existing_type=sa.BOOLEAN(),
        nullable=True
    )
    op.alter_column(
        'user', 'is_superuser',
        existing_type=sa.BOOLEAN(),
        nullable=True
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.alter_column(
        'user', 'is_superuser',
        existing_type=sa.BOOLEAN(),
        nullable=False
    )
    op.alter_column(
        'user', 'is_active',
        existing_type=sa.BOOLEAN(),
        nullable=False
    )
    op.drop_index(op.f('ix_wireguard_interface_peer_uuid'), table_name='wireguard_interface_peer')
    op.drop_table('wireguard_interface_peer')
    op.drop_index(op.f('ix_wireguard_interface_uuid'), table_name='wireguard_interface')
    op.drop_table('wireguard_interface')
    # ### end Alembic commands ###
